export * from './avatars'
export * from './icons'
export { default as AnimatedSet1 } from './illustrations/animated_set_1/AnimatedSet1'
export * from './svg-components/CategoryCard'
export { default as IconCard } from './svg-components/IconCard'
